CREATE TABLE EMP (
  EMP_NO CHAR(2),
  EMP_NAME VARCHAR2(10),
  SALARY INTEGER,
  MARITAL_STATUS CHAR check(MARITAL_STATUS IN ('S', 'M', 'D', 'W')),
  CONSTRAINT EMP_PKEY Primary Key (EMP_NO),
);

CREATE TABLE DEPT (
  DEPT_NO CHAR(2),
  DEPT_NAME VARCHAR2(10),
  MANAGER_NO CHAR(2),
  BUDGET INTEGER,
  CONSTRAINT DEPT_PKEY Primary Key (DEPT_NO),
);

CREATE TABLE PROJ (
  PROJ_NO CHAR(2),
  START_DATE DATE,
  DEADLINE DATE,
  CONSTRAINT PROJ_PKEY Primary Key (PROJ_NO)
)¬