DROP TABLE COUNTIES CASCADE CONSTRAINTS PURGE;
DROP TABLE TOWNS_AND_CITIES CASCADE CONSTRAINTS PURGE;
DROP TABLE AREAS CASCADE CONSTRAINTS PURGE;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS PURGE;
DROP TABLE BRANCH CASCADE CONSTRAINTS PURGE;
DROP TABLE STAFF CASCADE CONSTRAINTS PURGE;
DROP TABLE PAYROLL_DETAILS CASCADE CONSTRAINTS PURGE;
DROP TABLE PROPERTIES CASCADE CONSTRAINTS PURGE;
DROP TABLE PROP_OWNER CASCADE CONSTRAINTS PURGE;
DROP TABLE PROP_ADDR CASCADE CONSTRAINTS PURGE;
DROP TABLE PROP_ROOMS CASCADE CONSTRAINTS PURGE;
DROP TABLE SOLD_PROPERTIES CASCADE CONSTRAINTS PURGE;
DROP TABLE RENTED_PROPERTIES CASCADE CONSTRAINTS PURGE;
DROP TABLE DPS CASCADE CONSTRAINTS PURGE;
DROP TABLE ESTATE_AGENT CASCADE CONSTRAINTS PURGE;
DROP TABLE VIEWING CASCADE CONSTRAINTS PURGE;
DROP TABLE VIEWING_COMMENTS CASCADE CONSTRAINTS PURGE;

-- Drop Procedures


